### ISSUE TITLE
Unable dump dex: Error: missing argument

### ISSUE THREAD

**Issue by wcute** [hluwa/FRIDA-DEXDump#21] opened 2020-11-25 10:20 UTC
[Except] - Unable dump dex: Error: missing argument
    at frida/runtime/core.js:225
    at scandex (/script1.js:117)
    at frida/runtime/message-dispatcher.js:45
    at o (frida/runtime/message-dispatcher.js:27) in
  File "d:\python37\lib\site-packages\frida\core.py", line 333, in _rpc_request
    raise result[2]

**Comment by hluwa** [comment] 2020-11-28 09:45
Duplicate of #4

**Closed** 2020-12-28 03:25 UTC
